import { Component, OnInit } from '@angular/core';
import { ColumnTypes, TableColumn } from 'app/components/tablecomponent/models';
import { MainBaseComponent } from 'app/components/main-base/main-base.component';


enum TABS { OPEN, CLOSED, }
enum TOP_ACTIONS { CREATE_NEW, }



@Component({
  selector: 'ngx-eligibility-list',
  templateUrl: './eligibility-list.component.html',
  styleUrls: ['./eligibility-list.component.scss']
})
export class EligibilityListComponent extends MainBaseComponent {
  topActionButtons = [
    { name: 'CREATE_NEW', label: 'Create new', icon: 'plus', outline: false },
  ];
  TOP_ACTIONS = TOP_ACTIONS;
  TABS = TABS;
  selectedTab = TABS.OPEN;
  tableColumns = [
    { name: 'date', title: 'Name' },
    { name: 'date', title: 'Date Created' },
    { name: 'date', title: 'Generated By' },
    { name: 'date', title: 'Status' }
  ];
}
