import { Component, OnInit } from '@angular/core';

enum TOP_ACTIONS {
  ADD_NEW,
  INITIATE_VOLUNTARY_EXIT
}


@Component({
  selector: 'ngx-promotioneligibility',
  templateUrl: './promotioneligibility.component.html',
  styleUrls: ['./promotioneligibility.component.scss']
})
export class PromotioneligibilityComponent implements OnInit {
  showAddPlanModal = false
  topActionButtons = [
    { name: TOP_ACTIONS.ADD_NEW, label: 'Add New', 'icon': 'plus', outline: false },
    
  ];
   
  tableColumns = [
    { name: 'a', title: 'S/N' },
    { name: 'b', title: 'NAME' },
    { name: 'c', title: 'DATE CREATED' },
    { name: 'd', title: 'GENERATED BY' },
    { name: 'e', title: 'STATUS' },
 
  ];

  constructor() { }

  ngOnInit(): void {
  }
 
  modal(buttion) {
    if (buttion === TOP_ACTIONS.ADD_NEW) {
      this.showAddPlanModal = true;
    }
  //  if (buttion === TOP_ACTIONS.ADD_PLAN) {
     // this.showLeavePlanModal = true;
   // }
  }

}
